//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonBudget
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BddBudget : DbContext
    {
        public BddBudget()
            : base("name=BddBudget")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CEnregistrement> enregistrements { get; set; }
        public DbSet<CGroupe> groupes { get; set; }
        public DbSet<CType> types { get; set; }
        public DbSet<VueEnregistrements> allenregistrement { get; set; }
    }
}
