//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonBudget
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEnregistrement
    {
        public int enregistrement_id { get; set; }
        public string enregistrement_libelle { get; set; }
        public double enregistrement_valeur { get; set; }
        public int type_id { get; set; }
        public int group_id { get; set; }
    
        public virtual CGroupe groupe { get; set; }
        public virtual CType type { get; set; }
    }
}
