//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonBudget
{
    using System;
    using System.Collections.Generic;
    
    public partial class CType
    {
        public CType()
        {
            this.enregistrements = new HashSet<CEnregistrement>();
        }
    
        public int type_id { get; set; }
        public string type_libelle { get; set; }
    
        public virtual ICollection<CEnregistrement> enregistrements { get; set; }
    }
}
